kind: Kustomization

resources:
- https://github.com/envoyproxy/gateway/releases/download/v1.4.2/install.yaml

patches:
- path: envoy_gateway_patch.yaml
- target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: backendtlspolicies.gateway.networking.k8s.io
  patch: |
    $patch: delete
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: not-important
- target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: gatewayclasses.gateway.networking.k8s.io
  patch: |
    $patch: delete
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: not-important
- target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: gateways.gateway.networking.k8s.io
  patch: |
    $patch: delete
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: not-important
- target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: grpcroutes.gateway.networking.k8s.io
  patch: |
    $patch: delete
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: not-important
- target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: httproutes.gateway.networking.k8s.io
  patch: |
    $patch: delete
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: not-important
- target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: referencegrants.gateway.networking.k8s.io
  patch: |
    $patch: delete
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: not-important
- target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: tcproutes.gateway.networking.k8s.io
  patch: |
    $patch: delete
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: not-important
- target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: tlsroutes.gateway.networking.k8s.io
  patch: |
    $patch: delete
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: not-important
- target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: udproutes.gateway.networking.k8s.io
  patch: |
    $patch: delete
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: not-important
- target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: xbackendtrafficpolicies.gateway.networking.x-k8s.io
  patch: |
    $patch: delete
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: not-important
- target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: xlistenersets.gateway.networking.x-k8s.io
  patch: |
    $patch: delete
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: not-important



images:
- name: envoyproxy/gateway
  newName: envoyproxy/gateway
  newTag: v1.4.2

