apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager.yaml
- issuer.yaml

namespace: cert-manager

patches:
- path: patch.yaml
  target:
    kind: Deployment
    name: cert-manager
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/args
      value:
        - --v=2
        - --leader-election-namespace=cert-manager
  target:
    kind: Deployment
    name: cert-manager-cainjector