- op: replace
  path: /spec/template/spec/containers/0/args
  value:
    - --v=2
    - --cluster-resource-namespace=$(POD_NAMESPACE)
    - --leader-election-namespace=cert-manager
    - --acme-http01-solver-image=quay.io/jetstack/cert-manager-acmesolver:v1.18.2
    - --max-concurrent-challenges=60
    - --enable-gateway-api
