apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acebutt-cert
spec:
  dnsNames:
    - acebutt.xyz
    - '*.acebutt.xyz'
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: acebutt-cert
  usages:
    - digital signature
    - key encipherment