apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
- https://raw.githubusercontent.com/traefik/traefik-helm-chart/refs/tags/v36.3.0/traefik-crds/crds-files/traefik/traefik.io_ingressroutes.yaml
- https://raw.githubusercontent.com/traefik/traefik-helm-chart/refs/tags/v36.3.0/traefik-crds/crds-files/traefik/traefik.io_ingressroutetcps.yaml
- https://raw.githubusercontent.com/traefik/traefik-helm-chart/refs/tags/v36.3.0/traefik-crds/crds-files/traefik/traefik.io_ingressrouteudps.yaml
- https://raw.githubusercontent.com/traefik/traefik-helm-chart/refs/tags/v36.3.0/traefik-crds/crds-files/traefik/traefik.io_middlewares.yaml
- https://raw.githubusercontent.com/traefik/traefik-helm-chart/refs/tags/v36.3.0/traefik-crds/crds-files/traefik/traefik.io_middlewaretcps.yaml
- https://raw.githubusercontent.com/traefik/traefik-helm-chart/refs/tags/v36.3.0/traefik-crds/crds-files/traefik/traefik.io_serverstransports.yaml
- https://raw.githubusercontent.com/traefik/traefik-helm-chart/refs/tags/v36.3.0/traefik-crds/crds-files/traefik/traefik.io_serverstransporttcps.yaml
- https://raw.githubusercontent.com/traefik/traefik-helm-chart/refs/tags/v36.3.0/traefik-crds/crds-files/traefik/traefik.io_tlsoptions.yaml
- https://raw.githubusercontent.com/traefik/traefik-helm-chart/refs/tags/v36.3.0/traefik-crds/crds-files/traefik/traefik.io_tlsstores.yaml
- https://raw.githubusercontent.com/traefik/traefik-helm-chart/refs/tags/v36.3.0/traefik-crds/crds-files/traefik/traefik.io_traefikservices.yaml
# - cert.yaml

helmCharts:
- name: traefik
  repo: https://traefik.github.io/charts
  version: v36.3.0
  releaseName: traefik
  namespace: traefik
  valuesFile: values.yaml

patches:
- patch: |
    - op: add
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: 'argocd.acebutt.xyz,infer.acebutt.xyz,zot.acebutt.xyz'
  target:
    kind: Service
    name: traefik
# - patch: |
#     - op: remove
#       path: /spec/listeners/0
#   target:
#     kind: Gateway
#     name: traefik-gateway
#     namespace: traefik