apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

labels:
- includeSelectors: true
  pairs:
    app: metrics-server

resources:
- https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.8.0/components.yaml
