apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zot

resources:
- httproute.yaml

helmCharts:
  - name: zot
    repo: https://zotregistry.dev/helm-charts
    version: 0.1.66
    releaseName: zot
    namespace: zot
    valuesFile: values.yaml