apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: base
    repo: oci://gcr.io/istio-testing/charts
    version: 1.27-alpha.0551127f00634403cddd4634567e65a8ecc499a7
    releaseName: istio-base
    namespace: istio-system
  - name: istiod
    repo: oci://gcr.io/istio-testing/charts
    version: 1.27-alpha.0551127f00634403cddd4634567e65a8ecc499a7
    releaseName: istiod
    namespace: istio-system
    valuesInline:
      tag: 1.27-alpha.0551127f00634403cddd4634567e65a8ecc499a7
      hub: gcr.io/istio-testing
