apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: ome-system
data:
  deploy: |-
    {
      "defaultDeploymentMode": "RawDeployment"
    }
  ingress: >-
    {
        "ingressGateway" : "knative-serving/knative-ingress-gateway",
        "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local",
        "localGateway" : "knative-serving/knative-local-gateway",
        "localGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local",
        "knativeLocalGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local",
        "omeIngressGateway" : "",
        "ingressDomain"  : "svc.cluster.local",
        "ingressClassName" : "istio",
        "additionalIngressDomains" : null,
        "domainTemplate": "{{ .Name }}.{{ .Namespace }}.{{ .IngressDomain }}",
        "urlScheme": "http",
        "disableIstioVirtualHost": true,
        "pathTemplate": "",
        "disableIngressCreation": true,
        "enableGatewayAPI": false
    }
  kedaConfig: >-
    {
      "enableKeda" : true,
      "promServerAddress": "http://prometheus-operated.monitoring.svc.cluster.local:9090",
      "customPromQuery": "",
      "scalingThreshold": "10",
      "scalingOperator": "GreaterThanOrEqual"
    }
  metricsAggregator: |-
    {
      "enableMetricAggregation": "false",
      "enablePrometheusScraping" : "false"
    }
  modelInit: |-
    {
        "image" : "ghcr.io/moirai-internal/ome-agent:v0.1.3",
        "memoryRequest": "150Gi",
        "memoryLimit": "180Gi",
        "cpuRequest": "15",
        "cpuLimit": "15",
        "compartmentId": "ocid1.compartment.oc1..dummy-compartment",
        "authType" : "InstancePrincipal",
        "vaultId": "ocid1.vault.oc1.ap-osaka-1.dummy.dummy-vault",
        "region": "ap-osaka-1"
    }
  multinodeProber: |-
    {
        "image" : "ghcr.io/moirai-internal/multinode-prober:v0.1.3",
        "memoryRequest": "100Mi",
        "memoryLimit": "100Mi",
        "cpuRequest": "100m",
        "cpuLimit": "100m",
        "startupFailureThreshold": 150,
        "startupPeriodSeconds": 30,
        "startupTimeoutSeconds": 60,
        "startupInitialDelaySeconds": 120,
        "unavailableThresholdSeconds": 600
    }
  servingSidecar: |-
    {
        "image" : "ghcr.io/moirai-internal/ome-agent:v0.1.3",
        "memoryRequest": "2Gi",
        "memoryLimit": "4Gi",
        "cpuRequest": "1",
        "cpuLimit": "2",
        "compartmentId": "ocid1.compartment.oc1..dummy-compartment",
        "authType" : "InstancePrincipal",
        "region": "ap-osaka-1"
    }