apiVersion: v1
kind: Namespace
metadata:
  name: llama-70b-demo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-storage
  namespace: llama-70b-demo
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Ti
  csi:
    driver: csi.vastdata.com
    volumeAttributes:
      mount_options: vers=3,nconnect=16,lookupcache=pos,noacl,noatime
      protocol: NFS
      quota_id: "1498"
      root_export: /k8s
      storage.kubernetes.io/csiProvisionerIdentity: 1752419779638-8081-csi.vastdata.com
      tenant_id: "245"
      view_id: "1753"
      view_policy: nosquash-eb4403-ace-future-is-now-mSyv7E
      vip_pool_fqdn: U36A.all-tenants.storage-backend01.us-west-04a.int.coreweave.cloud
      volume_name: ngcp-eb4403-ace-future-is-now-mSyv7E:llm-d:pvc-7238e8dd-65cf-40c1-b953-21123c7567b6
    volumeHandle: pvc-7238e8dd-65cf-40c1-b953-21123c7567b6
  mountOptions:
    - vers=3
    - nconnect=16
    - lookupcache=pos
    - noacl
    - noatime
  persistentVolumeReclaimPolicy: Retain
  storageClassName: shared-vast
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage
  namespace: llama-70b-demo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  storageClassName: shared-vast
  volumeName: model-storage
---
apiVersion: ome.io/v1beta1
kind: ClusterBaseModel
metadata:
  name: llama-3-1-70b-instruct
spec:
  vendor: meta
  disabled: false
  version: "1.0.0"
  displayName: meta.llama-3.1-70b-instruct
  storage:
    storageUri: hf://meta-llama/Llama-3.1-70B-Instruct
    # storageUri: pvc://llama-70b-demo:model-storage/meta-llama/Llama-3.1-70B-Instruct
    nodeSelector:
      gpu.nvidia.com/model: H200
    path: /mnt/local/models/meta-llama/Llama-3.1-70B-Instruct
    key: hf-token
  modelFramework:
    name: transformers
    version: "4.47.0.dev0"
  modelFormat:
    name: safetensors
    version: "1.0.0"
  modelArchitecture: LlamaForCausalLM
---
apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: llama-3-1-70b-instruct-srt
  namespace: llama-70b-demo
spec:
  model:
    name: llama-3-1-70b-instruct
  engine:
    minReplicas: 1
    maxReplicas: 1
  runtime:
    name: srt-llama-3-3-70b-instruct
  # decoder:
  #   minReplicas: 1
  #   maxReplicas: 1
---
apiVersion: ome.io/v1beta1
kind: InferenceService
metadata:
  name: llama-3-1-70b-instruct-vllm
  namespace: llama-70b-demo
spec:
  model:
    name: llama-3-1-70b-instruct
  engine:
    minReplicas: 1
    maxReplicas: 1
  runtime:
    name: vllm-llama-3-3-70b-instruct
  # decoder:
  #   minReplicas: 1
  #   maxReplicas: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: llama-3-1-70b-instruct
  namespace: llama-70b-demo
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
  hostnames:
    - ome.acebutt.xyz
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
          headers:
          - name: Model
            value: llama-3-1-70b-instruct-srt
      backendRefs:
        - name: llama-3-1-70b-instruct-srt-engine
          port: 8080
          weight: 1
    - matches:
        - path:
            type: PathPrefix
            value: /
          headers:
          - name: Model
            value: llama-3-1-70b-instruct-vllm
      backendRefs:
        - name: llama-3-1-70b-instruct-vllm-engine
          port: 8080
          weight: 1