apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llm-d

resources:
- https://raw.githubusercontent.com/llm-d/llm-d-deployer/6993eee2a499ff5571b8ad17d3a91a814b6ab83a/charts/llm-d/crds/modelservice-crd.yaml

patches:
- patch: |
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: docker.io/alexeldeib/llm-d-model-service:0.0.1-lws-dev@sha256:d03a03ef5c88b3fffd33f0debdd68efdd7c15b2481e0bffdc869764ca7941991
    - op: replace
      path: /spec/template/spec/containers/0/args
      value:
        - run
        - --leader-elect=false
        - --health-probe-bind-address=:8081
        - --epp-cluster-role
        - llm-d-modelservice-endpoint-picker
        - --epp-pull-secrets
        - ""
        - --pd-pull-secrets
        - ""
  target:
    kind: Deployment
    name: llm-d-modelservice
- path: llm-d.ai_modelservices.yaml
  target:
    kind: CustomResourceDefinition
    name: modelservices.llm-d.ai

helmCharts:
  - name: llm-d
    repo: https://llm-d.ai/llm-d-deployer
    version: 1.0.22
    releaseName: llm-d
    namespace: llm-d
    valuesFile: values.yaml
    additionalValuesFiles: 
    - all-features.yaml
    # valuesInline:
    #   gateway:
    #     enabled: false
    #     gatewayClassName: istio
    #   sampleApplication:
    #     baseConfigMapRefName: basic-gpu-with-nixl-and-redis-lookup-preset
    #     model:
    #       modelArtifactURI: hf://meta-llama/Llama-3.2-3B-Instruct
    #       modelName: "meta-llama/Llama-3.2-3B-Instruct"
    #   redis:
    #     enabled: true
    #   modelservice:
    #     metrics:
    #       enabled: true
    #     epp:
    #       defaultEnvVarsOverride:
    #         - name: ENABLE_KVCACHE_AWARE_SCORER
    #           value: "true"
    #         - name: ENABLE_PREFIX_AWARE_SCORER
    #           value: "true"
    #         - name: ENABLE_LOAD_AWARE_SCORER
    #           value: "true"
    #         - name: ENABLE_SESSION_AWARE_SCORER
    #           value: "true"
    #         - name: PD_ENABLED
    #           value: "true"
    #         - name: PD_PROMPT_LEN_THRESHOLD
    #           value: "10"
    #         - name: PREFILL_ENABLE_KVCACHE_AWARE_SCORER
    #           value: "true"
    #         - name: PREFILL_ENABLE_LOAD_AWARE_SCORER
    #           value: "true"
    #         - name: PREFILL_ENABLE_PREFIX_AWARE_SCORER
    #           value: "true"
    #         - name: PREFILL_ENABLE_SESSION_AWARE_SCORER
    #           value: "true"
        