apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: buildkit-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: amd64-builder
spec:
  dnsNames:
    - build-amd64.acebutt.xyz
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: buildkit-issuer
  secretName: amd64-builder
  usages:
    - digital signature
    - key encipherment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: buildkitd-amd64
  name: buildkitd-amd64
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildkitd-amd64
  template:
    metadata:
      labels:
        app: buildkitd-amd64
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: cohere.com/buildkit-remote-agent
                    operator: In
                    values:
                      - preferred
      containers:
        - name: buildkitd
          image: moby/buildkit:v0.19.0
          args:
            - --addr
            - unix:///run/buildkit/buildkitd.sock
            - --addr
            - tcp://0.0.0.0:1234
            - --tlscacert
            - /certs/ca.crt
            - --tlscert
            - /certs/tls.crt
            - --tlskey
            - /certs/tls.key
            - --allow-insecure-entitlement=network.host
            - --allow-insecure-entitlement=security.insecure
          # the probe below will only work after Release v0.6.3
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 5
          # the probe below will only work after Release v0.6.3
          livenessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 64
              memory: 1Ti
              ephemeral-storage: 2000Gi
          securityContext:
            privileged: true
          ports:
            - containerPort: 1234
          volumeMounts:
            - name: certs
              readOnly: true
              mountPath: /certs
            - name: var-lib-buildkit
              mountPath: /var/lib/buildkit
            - mountPath: /etc/buildkit
              mountPropagation: None
              name: config
      volumes:
        # buildkit-daemon-certs must contain ca.pem, cert.pem, and key.pem
        - name: certs
          secret:
            secretName: amd64-builder
        - name: var-lib-buildkit
          emptyDir: { sizeLimit: 2000Gi }
        - configMap:
            defaultMode: 420
            name: buildkit-remote-agent-tls
            optional: false
          name: config
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: build-amd64.acebutt.xyz
    service.beta.kubernetes.io/coreweave-load-balancer-ip-families: ipv4
    service.beta.kubernetes.io/coreweave-load-balancer-type: public
  labels:
    app: buildkitd-amd64
  name: buildkitd-amd64
spec:
  type: LoadBalancer
  ports:
    - port: 1234
      protocol: TCP
  selector:
    app: buildkitd-amd64
---