apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
- https://github.com/argoproj/argo-cd/manifests/crds?ref=v3.0.11
- https://raw.githubusercontent.com/argoproj/argo-cd/refs/tags/v3.0.11/manifests/namespace-install.yaml
- gateway.yaml

patches:
- patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --insecure
  target:
    kind: Deployment
    name: argocd-server