apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./dependencies
# - https://github.com/vllm-project/aibrix/releases/download/v0.3.0/aibrix-dependency-v0.3.0.yaml
- https://github.com/vllm-project/aibrix/releases/download/v0.3.0/aibrix-core-v0.3.0.yaml


patches:
- target:
    kind: Gateway
    name: aibrix-eg
    namespace: aibrix-system
  patch: |
    apiVersion: gateway.networking.k8s.io/v1
    kind: Gateway
    metadata:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        cert-manager.io/common-name: "aibrix.acebutt.xyz"
      name: aibrix-eg
      namespace: aibrix-system
    spec:
      infrastructure:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: aibrix.acebutt.xyz
          service.beta.kubernetes.io/coreweave-load-balancer-ip-families: ipv4
          service.beta.kubernetes.io/coreweave-load-balancer-type: public
      listeners:
      # - name: http
      #   port: 80
      #   protocol: HTTP
      #   hostname: aibrix.acebutt.xyz
      - name: https
        port: 443
        protocol: HTTPS
        hostname: aibrix.acebutt.xyz
        tls:
          mode: Terminate
          certificateRefs:
          - kind: Secret
            name: aibrix-https